In [7]:
import numpy as np
import torch

1. Numpy与PyTorch的对比

In [11]:
# NumPy数组
np_array = np.array([[1, 2], [3, 4]])
print(f"NumPy数组:\n{np_array}")
print(f"形状: {np_array.shape}, 类型: {np_array.dtype}")

# PyTorch张量
torch_tensor = torch.tensor([[1, 2], [3, 4]])
print(f"\nPyTorch张量:\n{torch_tensor}")
print(f"形状: {torch_tensor.shape}, 类型: {torch_tensor.dtype}")
print(f"设备: {torch_tensor.device}")  # PyTorch独有！

NumPy数组:
[[1 2]
 [3 4]]
形状: (2, 2), 类型: int32

PyTorch张量:
tensor([[1, 2],
        [3, 4]])
形状: torch.Size([2, 2]), 类型: torch.int64
设备: cpu


2. 创建Tensor的12种方式

In [12]:
print("PyTorch创建Tensor的12种方式")
print("=" * 50)

# 1. torch.tensor() - 从Python数据创建（最常用）
data = [[1, 2], [3, 4]]
t1 = torch.tensor(data)
print(f"1. torch.tensor(): \n{t1}")

# 2. torch.from_numpy() - NumPy数组转换
np_array = np.array([[5, 6], [7, 8]])
t2 = torch.from_numpy(np_array)  # 共享内存！
print(f"\n2. torch.from_numpy(): \n{t2}")

# 3. torch.zeros() - 全0张量
t3 = torch.zeros(2, 3)  # 2行3列
print(f"\n3. torch.zeros(2,3): \n{t3}")

# 4. torch.ones() - 全1张量
t4 = torch.ones(2, 3)
print(f"\n4. torch.ones(2,3): \n{t4}")

# 5. torch.eye() - 单位矩阵
t5 = torch.eye(3)  # 3×3单位矩阵
print(f"\n5. torch.eye(3): \n{t5}")

# 6. torch.empty() - 未初始化张量（注意：值是随机的！）
t6 = torch.empty(2, 3)
print(f"\n6. torch.empty(2,3): \n{t6}")

# 7. torch.rand() - [0,1)均匀分布
t7 = torch.rand(2, 3)
print(f"\n7. torch.rand(2,3): \n{t7}")

# 8. torch.randn() - 标准正态分布 N(0,1)
t8 = torch.randn(2, 3)
print(f"\n8. torch.randn(2,3): \n{t8}")

# 9. torch.randint() - 整数随机数
t9 = torch.randint(0, 10, (2, 3))  # [0,10)的整数
print(f"\n9. torch.randint(0,10,(2,3)): \n{t9}")

# 10. torch.arange() - 等差序列
t10 = torch.arange(0, 10, 2)  # 0到10，步长2
print(f"\n10. torch.arange(0,10,2): {t10}")

# 11. torch.linspace() - 等间隔序列
t11 = torch.linspace(0, 1, 5)  # 0到1，等分5份
print(f"\n11. torch.linspace(0,1,5): {t11}")

# 12. torch.full() - 填充指定值
t12 = torch.full((2, 3), 3.14)  # 2×3矩阵，填充3.14
print(f"\n12. torch.full((2,3),3.14): \n{t12}")

PyTorch创建Tensor的12种方式
1. torch.tensor(): 
tensor([[1, 2],
        [3, 4]])

2. torch.from_numpy(): 
tensor([[5, 6],
        [7, 8]], dtype=torch.int32)

3. torch.zeros(2,3): 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

4. torch.ones(2,3): 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

5. torch.eye(3): 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

6. torch.empty(2,3): 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

7. torch.rand(2,3): 
tensor([[0.1140, 0.3277, 0.6931],
        [0.3138, 0.9770, 0.8915]])

8. torch.randn(2,3): 
tensor([[-0.9409,  0.4144,  0.1627],
        [ 1.5300, -1.3503, -0.3013]])

9. torch.randint(0,10,(2,3)): 
tensor([[3, 3, 0],
        [3, 7, 3]])

10. torch.arange(0,10,2): tensor([0, 2, 4, 6, 8])

11. torch.linspace(0,1,5): tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

12. torch.full((2,3),3.14): 
tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])


3. Tensor的核心属性

In [13]:
# 创建一个示例Tensor
x = torch.randn(2, 3, 4)  # 2个3×4矩阵

print("Tensor属性检查：")
print(f"1. 形状 shape: {x.shape}")         # torch.Size([2, 3, 4])
print(f"2. 维度 dim/ndim: {x.dim()}")      # 3维
print(f"3. 元素总数 numel: {x.numel()}")   # 2×3×4=24
print(f"4. 数据类型 dtype: {x.dtype}")     # torch.float32
print(f"5. 存储设备 device: {x.device}")   # cpu 或 cuda:0
print(f"6. 是否求导 requires_grad: {x.requires_grad}")  # False
print(f"7. 梯度 grad: {x.grad}")           # None（未计算梯度）
print(f"8. 步长 stride: {x.stride()}")     # (12, 4, 1) - 内存布局

Tensor属性检查：
1. 形状 shape: torch.Size([2, 3, 4])
2. 维度 dim/ndim: 3
3. 元素总数 numel: 24
4. 数据类型 dtype: torch.float32
5. 存储设备 device: cpu
6. 是否求导 requires_grad: False
7. 梯度 grad: None
8. 步长 stride: (12, 4, 1)


4. 逐元素运算

In [7]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y = torch.tensor([5.0, 6.0, 7.0, 8.0])

print("逐元素运算:")
print(f"x = {x}")
print(f"y = {y}")
print(f"\n加法: {x + y}")           # 或 torch.add(x, y)
print(f"减法: {x - y}")           # 或 torch.sub(x, y)
print(f"乘法: {x * y}")           # 或 torch.mul(x, y)
print(f"除法: {x / y}")           # 或 torch.div(x, y)
print(f"幂运算: {x ** 2}")        # 或 torch.pow(x, 2)
print(f"平方根: {torch.sqrt(x)}")  # 要求非负
print(f"指数: {torch.exp(x)}")
print(f"对数: {torch.log(x)}")

# 原地操作（节省内存）
x.add_(y)  # 等价于 x = x + y，但直接修改x
print(f"\n原地加法后 x = {x}")

逐元素运算:
x = tensor([1., 2., 3., 4.])
y = tensor([5., 6., 7., 8.])

加法: tensor([ 6.,  8., 10., 12.])
减法: tensor([-4., -4., -4., -4.])
乘法: tensor([ 5., 12., 21., 32.])
除法: tensor([0.2000, 0.3333, 0.4286, 0.5000])
幂运算: tensor([ 1.,  4.,  9., 16.])
平方根: tensor([1.0000, 1.4142, 1.7321, 2.0000])
指数: tensor([ 2.7183,  7.3891, 20.0855, 54.5981])
对数: tensor([0.0000, 0.6931, 1.0986, 1.3863])

原地加法后 x = tensor([ 6.,  8., 10., 12.])


5. 矩阵运算（深度学习核心！）

In [ ]:
# 创建矩阵
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
v = torch.tensor([2, 3], dtype=torch.float32)

print("矩阵运算演示:")
print(f"A:\n{A}")
print(f"B:\n{B}")
print(f"v: {v}")

print("\n1. 矩阵乘法:")
print(f"A @ B:\n{A @ B}")                  # Python 3.5+ 语法
print(f"torch.matmul(A, B):\n{torch.matmul(A, B)}")
print(f"A.mm(B):\n{A.mm(B)}")              # 专门用于矩阵乘法

print("\n2. 矩阵-向量乘法:")
print(f"A @ v: {A @ v}")
print(f"A.mv(v): {A.mv(v)}")

print("\n3. 转置:")
print(f"A.T:\n{A.T}")                      # 或 A.t()
print(f"torch.transpose(A, 0, 1):\n{torch.transpose(A, 0, 1)}")

print("\n4. 逆矩阵:")
if A.shape[0] == A.shape[1]:  # 方阵才有逆
    print(f"A.inverse():\n{A.inverse()}")  # 或 torch.inverse(A)

print("\n5. 行列式:")
print(f"torch.det(A): {torch.det(A)}")

矩阵运算演示:
A:
tensor([[1., 2.],
        [3., 4.]])
B:
tensor([[5., 6.],
        [7., 8.]])
v: tensor([2., 3.])

1. 矩阵乘法:
A @ B:
tensor([[19., 22.],
        [43., 50.]])
torch.matmul(A, B):
tensor([[19., 22.],
        [43., 50.]])
A.mm(B):
tensor([[19., 22.],
        [43., 50.]])

2. 矩阵-向量乘法:
A @ v: tensor([ 8., 18.])
A.mv(v): tensor([ 8., 18.])

3. 转置:
A.T:
tensor([[1., 3.],
        [2., 4.]])
torch.transpose(A, 0, 1):
tensor([[1., 3.],
        [2., 4.]])

4. 逆矩阵:
A.inverse():
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

5. 行列式:
torch.det(A): -2.0


6. 广播机制

In [ ]:
print("广播机制演示:")
# 情况1: 标量与Tensor
x = torch.tensor([[1, 2], [3, 4]])
print(f"x + 1:\n{x + 1}")  # 标量广播到整个矩阵

# 情况2: 不同形状Tensor
a = torch.tensor([[1, 2, 3]])        # 形状: (1, 3)
b = torch.tensor([[4], [5], [6]])    # 形状: (3, 1)
print(f"\na: {a.shape}, b: {b.shape}")
print(f"a + b:\n{a + b}")            # 广播为 (3, 3)

# 情况3: 自动扩展维度
c = torch.randn(3, 4, 5)
d = torch.randn(5)                   # 形状: (5,)
print(f"\nc: {c.shape}, d: {d.shape}")
print(f"c + d 可行: {(c + d).shape}")  # d广播为(1,1,5)再扩展为(3,4,5)

# 手动广播
e = torch.randn(3, 1, 4)
f = torch.randn(1, 5, 4)
print(f"\n手动广播:")
print(f"e.unsqueeze(1): {e.unsqueeze(1).shape}")  # 在位置1增加维度
print(f"f.expand(3, 5, 4): {f.expand(3, 5, 4).shape}")  # 扩展维度

广播机制演示:
x + 1:
tensor([[2, 3],
        [4, 5]])

a: torch.Size([1, 3]), b: torch.Size([3, 1])
a + b:
tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])

c: torch.Size([3, 4, 5]), d: torch.Size([5])
c + d 可行: torch.Size([3, 4, 5])

手动广播:
e.unsqueeze(1): torch.Size([3, 1, 1, 4])
f.expand(3, 5, 4): torch.Size([3, 5, 4])


7. 统计运算

In [13]:
x = torch.tensor([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]], dtype=torch.float32)

print("统计运算演示:")
print(f"原始Tensor:\n{x}")

print("\n1. 求和:")
print(f"所有元素和: {x.sum()}")            # 45
print(f"按列求和: {x.sum(dim=0)}")        # [12, 15, 18]
print(f"按行求和: {x.sum(dim=1)}")        # [6, 15, 24]

print("\n2. 均值:")
print(f"所有元素均值: {x.mean()}")         # 5.0
print(f"按列均值: {x.mean(dim=0)}")       # [4, 5, 6]

print("\n3. 极值:")
print(f"最大值: {x.max()}")                # 9
print(f"最大值及其索引: {x.max(dim=1)}")   # 每行最大值和索引

print("\n4. 其他统计量:")
print(f"标准差: {x.std()}")                # 2.5819887
print(f"方差: {x.var()}")                  # 6.6666665
print(f"中位数: {x.median()}")             # 5
print(f"众数: {torch.mode(x.flatten())}")  # 需要一维Tensor

print("\n5. 累加运算:")
print(f"累积和: {x.cumsum(dim=0)}")        # 按列累积
print(f"累积积: {x.cumprod(dim=1)}")       # 按行累积

统计运算演示:
原始Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

1. 求和:
所有元素和: 45.0
按列求和: tensor([12., 15., 18.])
按行求和: tensor([ 6., 15., 24.])

2. 均值:
所有元素均值: 5.0
按列均值: tensor([4., 5., 6.])

3. 极值:
最大值: 9.0
最大值及其索引: torch.return_types.max(
values=tensor([3., 6., 9.]),
indices=tensor([2, 2, 2]))

4. 其他统计量:
标准差: 2.7386128902435303
方差: 7.5
中位数: 5.0
众数: torch.return_types.mode(
values=tensor(1.),
indices=tensor(0))

5. 累加运算:
累积和: tensor([[ 1.,  2.,  3.],
        [ 5.,  7.,  9.],
        [12., 15., 18.]])
累积积: tensor([[  1.,   2.,   6.],
        [  4.,  20., 120.],
        [  7.,  56., 504.]])


8. GPU加速（CUDA）

In [5]:
print("GPU加速演示:")

# 检查GPU是否可用
if torch.cuda.is_available():
    print(f"GPU可用: {torch.cuda.get_device_name(0)}")
    
    # 创建Tensor并移到GPU
    cpu_tensor = torch.randn(1000, 1000)
    gpu_tensor = cpu_tensor.cuda()  # 或 .to('cuda')
    
    print(f"CPU Tensor设备: {cpu_tensor.device}")
    print(f"GPU Tensor设备: {gpu_tensor.device}")
    
    # 在GPU上进行计算
    gpu_result = gpu_tensor @ gpu_tensor.T
    
    # 移回CPU
    cpu_result = gpu_result.cpu()  # 或 .to('cpu')
    
    # 设备管理最佳实践
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    x = torch.randn(10, 10, device=device)  # 直接创建在指定设备
    print(f"直接创建在设备: {x.device}")
else:
    print("GPU不可用，使用CPU计算")

GPU加速演示:
GPU可用: NVIDIA GeForce RTX 5060 Laptop GPU
CPU Tensor设备: cpu
GPU Tensor设备: cuda:0
直接创建在设备: cuda:0


9. Tensor与NumPy互转

In [8]:
print("Tensor ↔ NumPy 无缝转换:")

# Tensor → NumPy
tensor = torch.tensor([[1, 2], [3, 4]])
numpy_array = tensor.numpy()  # 共享内存！
print(f"Tensor:\n{tensor}")
print(f"转换为NumPy:\n{numpy_array}")

# 修改NumPy会影响Tensor
numpy_array[0, 0] = 99
print(f"修改后Tensor:\n{tensor}")  # 也会被修改！

# NumPy → Tensor
np_array = np.array([[5, 6], [7, 8]])
tensor_from_np = torch.from_numpy(np_array)  # 同样共享内存
print(f"\nNumPy数组:\n{np_array}")
print(f"转换为Tensor:\n{tensor_from_np}")

# 不共享内存的转换（安全但耗内存）
tensor_copy = torch.tensor(np_array)  # 创建副本

Tensor ↔ NumPy 无缝转换:
Tensor:
tensor([[1, 2],
        [3, 4]])
转换为NumPy:
[[1 2]
 [3 4]]
修改后Tensor:
tensor([[99,  2],
        [ 3,  4]])

NumPy数组:
[[5 6]
 [7 8]]
转换为Tensor:
tensor([[5, 6],
        [7, 8]], dtype=torch.int32)


10. Tensor与NumPy的性能对比

In [9]:
import time

# 创建大型数组
size = 10000
np_arr = np.random.randn(size, size)
torch_tensor = torch.randn(size, size)

print("性能对比: NumPy vs PyTorch (CPU)")
print(f"数据大小: {size}×{size} = {size*size:,} 个元素")

# NumPy运算时间
start = time.time()
result_np = np_arr @ np_arr
np_time = time.time() - start
print(f"NumPy矩阵乘法: {np_time:.3f} 秒")

# PyTorch CPU运算时间
start = time.time()
result_torch = torch_tensor @ torch_tensor
torch_cpu_time = time.time() - start
print(f"PyTorch CPU乘法: {torch_cpu_time:.3f} 秒")

# PyTorch GPU运算时间（如果可用）
if torch.cuda.is_available():
    torch_gpu = torch_tensor.cuda()
    torch.cuda.synchronize()  # 等待CUDA操作完成
    start = time.time()
    result_gpu = torch_gpu @ torch_gpu
    torch.cuda.synchronize()
    torch_gpu_time = time.time() - start
    print(f"PyTorch GPU乘法: {torch_gpu_time:.3f} 秒")
    print(f"GPU加速比: {torch_cpu_time/torch_gpu_time:.1f}x")

性能对比: NumPy vs PyTorch (CPU)
数据大小: 10000×10000 = 100,000,000 个元素
NumPy矩阵乘法: 8.888 秒
PyTorch CPU乘法: 3.484 秒
PyTorch GPU乘法: 0.585 秒
GPU加速比: 6.0x


11. 自动求导

In [14]:
# PyTorch支持梯度跟踪
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x ** 2
y.sum().backward()
print(f"PyTorch梯度: {x.grad}")  # tensor([2., 4., 6.])

# NumPy没有自动求导功能
print("NumPy没有requires_grad和.grad属性")

PyTorch梯度: tensor([2., 4., 6.])
NumPy没有requires_grad和.grad属性
